parameters:
    fml.notification.listener.notificationsend.class: FML\Notification\NotificationBundle\EventListener\NotificationSendListener
    fml.notification.manager.class: FML\Notification\MessageManager
    fml.notification.manager.buffered.class: FML\Notification\BufferedMessageManager
    fml.notification.channel.mail.class: FML\Notification\Channel\Channel\SwiftMailerMailChannel

services:
    fml.notification.channel.mail:
        class: '%fml.notification.channel.mail.class%'
        arguments: ['@mailer']

    fml.notification.manager:
        class: '%fml.notification.manager.class%'
        calls:
            - [addChannel, ['@fml.notification.channel.mail']]

    fml.notification.manager.buffered:
        class: '%fml.notification.manager.buffered.class%'
        calls:
            - [addChannel, ['@fml.notification.channel.mail']]

    fml.notification.listener.notificationsend:
        class: '%fml.notification.listener.notificationsend.class%'
        arguments: ['@fml.notification.manager.buffered']
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: onTerminate }
